habilidades/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include("modules.landing.urls",namespace="landing")),

]

modules/landing/urls.py
#Urls de app landing
from django.conf.urls import url
from .views import index, index_get_template
app_name = 'landing'
urlpatterns = [
    url(r'^$',index, name="index"),
    url(r'^(?P<page>[\w]+)/$',index_get_template, name="index_get_template"),
    
]

modules/landing/models.py
from django.db import models

# Create your models here.

modules/landing/views.py
from django.shortcuts import render,redirect
from django.http import Http404
# Create your views here.
def index(request):
    return render(request,'landing/index.html')

def index_get_template(request,page):
    print(page)
    page = page + '.html'
    return render(request,'landing/'+page)

templates/base.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Habilidades para adolescentes</title>
  <link rel="shortcut icon" href="https://www.unam.mx/sites/default/files/favicon_0.ico" type="image/vnd.microsoft.icon">
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" href="{% static 'css/custom.css' %}">
   {%block css%}

    {%endblock%}
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <style>
    /* Remove the navbar's default margin-bottom and rounded borders */
  
    
   
    .navbar {
      margin-bottom: 0;
      border-radius: 0;
    }
    
    /* Set height of the grid so .sidenav can be 100% (adjust as needed) */
    .row.content {height: 450px}
    
    /* Set gray background color and 100% height */
    .sidenav {
      padding-top: 20px;
      background-color: #f1f1f1;
      height: 100%;
    }
    
    /* Set black background color, white text and some padding */
    footer {
      background-color: #555;
      color: white;
      padding: 15px;
    }
    
    /* On small screens, set height to 'auto' for sidenav and grid */
    @media screen and (max-width: 767px) {
      .sidenav {
        height: auto;
        padding: 15px;
      }
      .row.content {height:auto;} 
    }
  </style>
</head>
<body>

<div class="container-fluid encabezado">

  
<div class="col-sm-4">

         <img src="{% static 'images/logo_unam.png' %}"  class=img-responsive>
</div>
<div class="col-sm-8 subtitle">
	<br>
	<img src="{% static 'images/banner_habilidades_gris.png' %}" class=img-responsive aling="left">
    <!--h3>Habilidades para adolescentes</h3>
    <h4>Proyectos INFOCAB:PB200511-PB200714</h4-->
</div>

      
</div>

<div class="container-fluid text-center">    
	<div class="row content">
        <nav class="navbar navbar-inverse">
 
            <div class="container-fluid">
                <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>                        
                </button>
                
                <!--img class="navbar-brand" src="logo_hpa.png"-->
                </div>
                <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav">
                    <li><a href="{%url 'landing:index_get_template' page='index' %}">Inicio</a></li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Material didáctico
                        <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                        <li><a href="infocab_pb200511">INFOCAB PB200511</a></li>
                        <li><a href="infocab_pb200714">INFOCAB PB200714</a></li>
                        <li><a href="material_sihdyt">Material SIHDyT</a></li>
                        
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Emocionales
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                        <li><a href="{%url 'landing:index_get_template' page='habilidades_emocionales' %}">Habilidades emocionales</a></li>
                        <li><a href="{%url 'landing:index_get_template' page='autoestima' %}">Autoestima</a></li>
                        <li><a href="{%url 'landing:index_get_template' page='como_aumentar_la_autoestima' %}">¿Cómo aumentar la autoestima?</a></li>
                        
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Sociales
                        <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                        <li><a href="{%url 'landing:index_get_template' page='habilidades_sociales' %}">Habilidades sociales</a></li>
                        <li>
                                <a href="{%url 'landing:index_get_template' page='asertividad' %}">Asertividad</a>	 	
                        </li>
                        
                        
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Cognitivas
                        <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                        <li><a href="{%url 'landing:index_get_template' page='habilidades_cognitivas' %}">Habilidades cognitivas</a></li>
                        <li><a href="{%url 'landing:index_get_template' page='planear_para_la_vida' %}">Planear para la vida</a></li>
                        <li><a href="{%url 'landing:index_get_template' page='decisiones' %}">Decisiones</a></li>
                        <li><a href="{%url 'landing:index_get_template' page='metas' %}">Metas</a></li>
                    
                        
                        </ul>
                    </li>
                    <li><a href="#">E-book</a></li>
                    <li><a href="#">Contacto</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Iniciar sesión</a></li>
                </ul>
                </div>
            </div>
        </nav>
        <div class="col-sm-9 text-left">
            	{%block content%}

                {%endblock%}
        </div>

        <div class="col-sm-3 sidenav">
      			<div class="well">
        			<a href="http://diplomado.habilidadesparaadolescentes.com/index/" target="_blank"></p>
        			<img src="http://habilidadesparaadolescentes.com/images/avisolateral_DDHV4Gen.jpg">
      			</div>
      			<div class="well">
        			<a href="http://segundocoloquio.habilidadesparaadolescentes.com/index/" target="_blank">
        			<img src="http://habilidadesparaadolescentes.com/images/avisolateral_2CIE.jpg"></a>
      			</div>

    		</div>
  	</div>
</div>
<footer class="container-fluid text-center">
  <p>Hecho en México, Universidad Nacional Autónoma de México (UNAM), todos los derechos reservados 2017.</p>

<p>Esta página puede ser reproducida con fines no lucrativos, siempre y cuando no se mutile, se cite la fuente completa y su dirección electrónica.</p>
<p>De otra forma, requiere permiso previo por escrito de la institución.</p>



Última actualización: 08/02/2017
</footer>

</body>
</html>

templates/landing/asertividad.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<h2>Asertividad</h2>


<p>
La asertividad es una habilidad social y se refiere a la capacidad que tenemos para defender los derechos propios expresando lo que se cree, se piensa y se siente de manera clara y directa en el momento oportuno.
</p>
<p>
La asertividad es fundamental para manejar de manera clara y abierta las relaciones interpersonales, ya que permite tener un control personal sobre las diversas situaciones sociales que ha diario se nos presentan, y en donde se toman muchas decisiones que afectan nuestra vida como: fumar o no fumar, beber o no beber alcohol, tener o no tener relaciones sexuales, usar o no usar anticonceptivos, etc.
</p>

  <ul class="nav nav-tabs">
    <li class="active"><a data-toggle="tab" href="#caracteristicas">Caracteristicas de una persona asertiva</a></li>
    <li><a data-toggle="tab" href="#comunicacion">Comunicación asertiva</a></li>

  </ul>
  
    <div class="tab-content">
    <div id="caracteristicas" class="tab-pane fade in active">
      
      <p>
      		<ul>
      				<li>Ve y acepta la realidad.</li>
				<li>Actúa y habla con base en hechos concretos y objetivos.</li>
				<li>Toma decisiones por voluntad propia.</li>
				<li>Acepta sus errores y sus aciertos.</li>
				<li>Utiliza sus capacidades personales con gusto.</li>
				<li>No siente vergüenza de usar sus capacidades personales.</li>
				<li>Es auto afirmativo, siendo al mismo tiempo gentil y considerado.</li>
				<li>No es agresivo, está dispuesto a dirigir, así como, a dejar que otros dirijan.</li>
				<li>Puede madurar, desarrollarse y tener éxito, sin resentimientos.</li>
				<li>Permite que otros maduren, se desarrollen y tengan éxito.</li>
      		</ul>
      </p>
    </div>
    <div id="comunicacion" class="tab-pane fade">
      <p>
      <ul>
     	<li>Identificar lo que se piensa, lo que se siente y lo que se quiere.</li>
	<li>Aceptar nuestros pensamientos, sentimientos y creencias.</li>
	<li>Controlar los sentimientos que impiden la comunicación, de tal manera que no se permita que el temor o la ansiedad haga que no podamos expresarlo.</li>
	<li>Buscar el momento y la situación oportuna para decir lo que se quiere decir.</li>
	<li>Ser específicos al expresar nuestros sentimientos, deseos y pensamientos. No interpretar los mensajes de los demás.</li>
	<li>Una vez que se tiene clara la situación y lo que se va a decir, es importante dar respuestas concretas de manera rápida y directa.</li>
      </ul>
      </p>
    </div>
    </div>
{% endblock %}

templates/landing/autoestima.html
{% extends "base.html" %}
{% load static %}
{% block content %}
			<h2>Autoestima</h2>
			
			<p>
				Es la capacidad de tener confianza y respeto por sí mismo
			</p>
			
			<p>
				Es un proceso dinámico, que se inicia en el núcleo familiar, y se va fortaleciendo con las experiencias que se tienen a lo largo de la vida. Si la familia (principalmente los padres) proporcionan al niño cariño, seguridad, confianza y respeto, éste adquiere las bases para una autoestima adecuada, que le permitirá sentirse apto para afrontar las situaciones problemáticas de la vida.
					
			</p>
			<h3>Características</h3>
			<ul>
				<li>Es la confianza y respeto por nosotros mismos</li>
				<li>Se estructura a través del amor, respeto con que nos nutrieron desde niños.</li>
				<li>Debe ser sentida como parte de uno mismo.</li>
				<li>No necesita del reconocimiento externo ya que se posee el reconocimiento interno.</li>
				<li>Permite crecer libres, creativos, alegres, amistosos, amorosos, sentirnos plenos y con capacidad de dar y recibir.</li>
			</ul>

{% endblock %}

templates/landing/como_aumentar_la_autoestima.html
{% extends "base.html" %}
{% load static %}
{% block content %}
			<h2>¿Como aumentar la autoestima?</h2>

<ul>
	<li>Saber y aceptar que todos tenemos cualidades y defectos.</li>
	<li>Saber que todos tenemos algo bueno de lo cual podemos estar orgullosos.</li>
	<li>Liberarnos de conceptos negativos sobre nosotros mismos.</li>
	<li>Aceptar que todos somos importantes y valiosos.</li>
	<li>Vivir responsablemente de acuerdo a nuestra realidad, reconociendo lo que nos gusta y lo que nos disgusta.</li>
	<li>Aprender a aceptarnos a través de lo que sentimos y de lo que somos.</li>
	<li>Liberarnos de la culpa al evaluar lo que queremos y pensamos.</li>
	<li>Actuar de acuerdo a lo que deseamos, sentimos y pensamos, sin tener como base la aprobación o desaprobación de los demás.</li>
	<li>Sentirnos responsables de nosotros mismos.</li>
	<li>Fomentar la autoestima en otros.</li>
</ul>
{% endblock %}

templates/landing/decisiones.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<h2>Decisiones adecuadas</h2>



<p>
Con frecuencia nos hacemos esta pregunta. Las decisiones se toman cada hora de cada día, sea consciente o inconscientemente. Algunas de ellas como por ejemplo: ¿Qué carrera estudiar?, tienen que ser sopesadas a lo largo de un período de tiempo, mientras que otras son prácticamente automáticas, como ¿Qué desayuno hoy? Tu vida es la culminación de las decisiones que has tomado y cada nueva elección la cambia ligeramente. Comprender esto es crucial para mantener un buen enfoque con respecto a la toma de decisiones.
</p>
<h3>Como tomar decisiones adecuadas</h3>
<ul>
	<li>Identificar lo que se piensa, lo que se siente y lo que se quiere.</li>
	<li>Aceptar nuestros pensamientos, sentimientos y creencias.</li>
	<li>Controlar los sentimientos que impiden la comunicación, de tal manera que no se permita que el temor o la ansiedad haga que no podamos expresarlo.</li>
	<li>Buscar el momento y la situación oportuna para decir lo que se quiere decir.</li>
	<li>Ser específicos al expresar nuestros sentimientos, deseos y pensamientos. No interpretar los mensajes de los demás.</li>
	<li>Una vez que se tiene clara la situación y lo que se va a decir, es importante dar respuestas concretas de manera rápida y directa.</li>
</ul>
{% endblock %}

templates/landing/habilidades_cognitivas.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<h2>Habilidades cognitivas</h2>



	<table class="table-bordered table-condensed">
								<tr >
									<td rowspan="3">Conciencia de uno mismo</td>
									<td>Reconocer los sentimientos propios.</td>
								</tr>
								<tr >									
									<td>Saber definir nuestros sentimientos. ¿Qué es lo que realmente siento?.</td>
								</tr>
								<tr >									
									<td>Ser congruentes con nuestros pensamientos, sentimientos y acciones.</td>
								</tr>
								
								<tr >
									<td rowspan="3">Toma de decisiones personales</td>
									<td>Reflexionar sobre nuestros comportamientos y acciones para estar conscientes de sus consecuencias.</td>
								</tr>
								<tr >									
									<td>Identificar los pensamientos y/o sentimientos que están gobernando nuestras acciones o conductas.</td>
								</tr>
								<tr >									
									<td>Fijar metas y planear diversas acciones para poder alcanzarlas.</td>
								</tr>
							
							</table>

{% endblock %}

templates/landing/habilidades_emocionales.html
{% extends "base.html" %}
{% load static %}
{% block content %}
			<h2>Habilidades emocionales</h2>
			<table class="table-bordered table-condensed">

							<tbody>
							<tr>
								<td rowspan="4">Manejo de sentimientos</td>
								<td>Ser capaz de "conversar con uno mismo", a través de la reflexión sobre nuestras acciones y sentimientos.</td>
							</tr>
							<tr>
								<td>Analizar lo que hay detrás de un sentimiento, por ejemplo: si siento enojo: ¿por qué es ese enojo?</td>
								
							</tr>
							<tr>
								<td>Enfrentarse a los temores, la ansiedad, la ira, el estrés y la tristeza, a través de acciones concretas. Por ejemplo: reflexionar y realizar actividades placenteras y positivas para nosotros como: meditar, relajarnos y hacer ejercicio.</td>
								
							</tr>
							<tr>
								<td>Encontrar y sentir placer en todas las actividades diarias que realizamos.</td>
								
							</tr>

							<tr>
								<td rowspan="2">Empatía</td>
								<td>Entender que la gente puede tener sentimientos diferentes a los nuestros.</td>
							</tr>
							<tr>
								<td>Comprender los sentimientos y las preocupaciones de los demés desde su perspectiva.</td>
								
							</tr>
							
							<tr>
								<td rowspan="6">Aceptación y seguridad de uno mismo</td>
								<td>Identificar las pautas y normas que tenemos en nuestra vida emocional y reconocerlas en los demás.</td>
							</tr>
							<tr>
								<td>Sentir orgullo de uno mismo.</td>
								
							</tr>
							<tr>
								<td>Verse positivamente: reconocer los propios puntos débiles y los fuertes.</td>
								
							</tr>
							<tr>
								<td>Desarrollar expectativas realistas con respecto a uno mismo.</td>
								
							</tr>
							<tr>
								<td>Ser capaces de reírse de uno mismo.</td>
								
							</tr>
							<tr>
								<td>Manifestar nuestros pensamientos y sentimientos, evitando la ira y la pasividad.</td>
								
							</tr>

						</tbody>
						</table>
						<br>

{% endblock %}

templates/landing/habilidades_sociales.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<h2>Habilidades sociales</h2>
							<table class="table-bordered table-condensed">
								<tr >
									<td rowspan="5">Manejo de la comunicación</td>
									<td>Hablar claramente de lo que sentimos.</td>
								</tr>
								<tr>									
									<td>Saber escuchar y plantear preguntas cuando exista confusión en lo que nos tratan de comunicar.</td>
								</tr>
								<tr >									
									<td>Evitar que los prejuicios obstaculicen la comunicación interpersonal.</td>
								</tr>
								<tr >									
									<td>Valorar la apertura y crear confianza en una relación.</td>
								</tr>
								<tr >									
									<td>Identificar los momentos adecuados para hablar de sentimientos personales.</td>
								</tr>
								<tr >
									<td rowspan="5">Resolución de conflictos</td>
									<td>Aprender a cooperar y colaborar dentro de un grupo.</td>
								</tr>
								<tr >									
									<td>Ser tolerantes, comprensivos y negociadores.</td>
								</tr>
								<tr >									
									<td>Proponer nuestras ideas y juicios con base en hechos razonados.</td>
								</tr>
								<tr >									
									<td>Crear canales de comunicación.</td>
								</tr>
								<tr >									
									<td>Ser flexibles y evitar aferrarse a una idea, ya que esto interrumpe la comunicación.</td>
								</tr>
							</table>
							<br>

{% endblock %}

templates/landing/index.html
{%extends "base.html" %}
{% load static %}

{% block content %}

          
			<h3>Bienvenido</h3>
				<p><center>El objetivo de este sitio web es proporcionar a los profesores y alumnos adolescentes la información necesaria para adquirir o reforzar las habilidades emocionales, sociales y cognitivas que les permitan desarrollarse y enfrentar de manera exitosa los retos, dificultades y amenazas que durante su adolescencia se les presentan y lograr la transición a una edad adulta integra y plena.</center></p>
      			<hr>
			<div id="myCarousel" class="carousel slide" data-ride="carousel">
      				<!-- Indicators -->
      					<ol class="carousel-indicators">
        					<li data-target="#myCarousel" data-slide-to="0"></li>
        					<li data-target="#myCarousel" data-slide-to="1" class="active"></li>
      					</ol>
      					<div class="carousel-inner" role="listbox">
        					<div class="item">
        						<a href="http://segundocoloquio.habilidadesparaadolescentes.com/index" >
          							<img class="first-slide " src="{% static 'images/inicio_2doCIE.jpg' %}"  alt="First slide">
          						</a>
          						<div class="container">
           							
          						</div>
        					</div>
        					<div class="item active">
        						<a href="http://diplomado.habilidadesparaadolescentes.com/index" >
          							<img class="first-slide " src="{% static 'images/inicio_DHV4Gen.jpg' %}" alt="First slide">
          						</a>
          						<div class="container">
           							
          						</div>
        					</div>
        
      					</div>
      					<a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        					<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        					<span class="sr-only">Previous</span>
      					</a>
      					<a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        					<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        					<span class="sr-only">Next</span>
      					</a>

			</div>
    <br>

{% endblock %}

templates/landing/metas.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<h2>Metas</h2>

<p>Para alcanzar nuestras metas o aspiraciones, debemos sentirnos seguros de nosotros mismos, con control de las cosas que nos suceden, con un nivel alto de autoestima y con una clara conciencia de los valores personales que poseemos.
</p>

<h3>Como lograr nuestras metas</h3>

<ul>
	<li>Tener una autoestima alta y una jerarquía de valores.</li>
	<li>Planear el futuro a través de fijarse metas concretas, claras y específicas.</li>
	<li>Programar actividades específicas para llegar a cumplir nuestras metas.</li>
	<li>Hacer de cada experiencia una ocasión para aprender y afinar el conocimiento.</li>
	<li>Tener motivación para triunfar. Para triunfar en la vida hay que querer hacerlo, no tener miedo del triunfo y ser perseverantes en las actividades que nos conducen a alcanzar la meta que nos proponemos.</li>
</ul>
{% endblock %}

templates/landing/planear_para_la_vida.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<h2>Planear la vida</h2>



<p>
Planear la vida implica un proceso de reflexión objetiva en el que hay que considerar factores importantes: plantearte qué metas quieres según las área de desarrollo que te interesen: deportes, estudio, trabajo, relaciones sociales, familiares, etc. El proyectar tus metas de vida especificando las conductas, las condiciones y los tiempos te motivará para triunfar, es decir el que quieras hacerlo.
</p>

<p>
Para lograr lo anterior, debes tener clara tú jerarquía de valores en la cual debes incluir altas aspiraciones para ti mismo, estar en posición de decir que quieres y que necesitas para llevarlas a cabo, de esta manera, tendrá mayores posibilidades de no involucrarte en problemas que puedan interferir en tus objetivos de vida, por ejemplo, el hacer uso de sustancias que dañen tu bienestar, o tener riesgo asociados a la sexualidad como embarazos no deseados o infecciones de transmisión sexual.
</p>

<p>
Tú sabrás que realmente estas planeando tu vida cuando de manera asertiva establezcas y desarrolles una comunicación con quienes te rodean, actúes con base en valores propios, fortalezcas tu autoestima, tomes decisiones racionales sobre las metas que a corto, mediano y largo plazo hayas decidido, de manera consciente y que dirigirán tu vida.
</p>
{% endblock %}